server.port=8080

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.data.mongodb.uri=mongodb+srv://breketkelay:HzeLwFqweX5AGwvX@cluster0.ki2iu.mongodb.net/
spring.data.mongodb.database=AleNedaj
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=breketkelay@gmail.com
spring.mail.password=lwby abir rsfo hjar
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=your-super-secret-key
jwt.expiration=86400000

logging.level.org.springframework.data.mongodb.core=DEBUG

mapbox.api-key=pk.eyJ1IjoiYmVraS1rZWwiLCJhIjoiY2x0c3Z1MjljMHJqcTJqdWxldmFldHk5aCJ9.ynE4zgvTDBIYxk00E8kX_A